pipeline {
  options {
    buildDiscarder(logRotator(numToKeepStr: '10'))
  }

  triggers {
    cron('@daily')
  }

  agent {
    dockerfile {
        dir '.docker'
    }
  }

  stages {
    stage ('artifact retention') {
      environment {
        RTF_URL = 'http://localhost:8081/artifactory'
        RTF_CREDS = credentials('my-artifactory-credentials')
        CI = true
      }

      steps {
        script {
          sh './runRetention --url=$RTF_URL --user=$RTF_USR --password=$RTF_PSW'
        }
      }
    }
  }

  post {
    failure {
      mail(
        body: "Artifactory retention is failing, see run details over at ${env.JOB_URL}",
        subject: 'Artifactory retention is failing',
        to: 'rtf-support@place.hldr'
      )
    }
  }
}
